[package]
name = "test_project"
version = "0.1.0"
edition = "2024"

[dependencies]
bulletproofs = "4.0"
curve25519-dalek-ng = {version = "4.0", features = ["serde"]}
merlin = "3.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"